let all=[],filtered=[],page=1;const size=20,$=s=>document.querySelector(s),esc=s=>String(s??'').replace(/[&<>\"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[c]));
const authors=e=>(e.authors||[]).map(a=>a.name).join(', ')||'Unknown author',cls=e=>e.classification||{},tags=e=>[...(cls(e).arxiv||[]),...(cls(e).msc2020||[])];
function card(e){return `<article class="card"><div><a class="title" href="result.html?id=${encodeURIComponent(e.id)}">${esc(e.title)}</a><div class="subtitle">${esc(authors(e))} · ${esc(e.trust?.level||'')} · ${esc(e.status||'')}</div><p class="abstract">${esc(e.abstract||'暂None摘要')}</p><div class="tags">${tags(e).map(x=>`<span class="tag">${esc(x)}</span>`).join('')}</div></div><div class="side"><strong>v${esc(e.version)}</strong>${esc(e.published_at||'').slice(0,10)}<br>${esc(e.source?.repository||'')}</div></article>`}
function render(){let q=$('#q').value.toLowerCase(),a=$('#arxiv').value,m=$('#msc').value,s=$('#sort').value;filtered=all.filter(e=>{let t=JSON.stringify(e).toLowerCase();return(!q||t.includes(q))&&(!a||(cls(e).arxiv||[]).includes(a))&&(!m||(cls(e).msc2020||[]).includes(m))});filtered.sort((x,y)=>s==='title'?x.title.localeCompare(y.title):s==='version'?(y.versions||0)-(x.versions||0):String(y.published_at).localeCompare(String(x.published_at)));let pages=Math.max(1,Math.ceil(filtered.length/size));page=Math.min(page,pages);$('#rows').innerHTML=filtered.slice((page-1)*size,page*size).map(card).join('')||'<div class="empty">No matching results</div>';$('#count').textContent=`${filtered.length} 条Results`;$('#page').textContent=`第 ${page} / ${pages} 页`;$('#prev').disabled=page===1;$('#next').disabled=page===pages}
function fill(id,vals){let u=[...new Set(vals)].sort();$(id).innerHTML='<option value="">All categories</option>'+u.map(x=>`<option>${esc(x)}</option>`).join('')}
fetch('data/latest.json').then(r=>r.json()).then(x=>{all=x.results.entries||[];let c=x.changes||{};$('#status').textContent=`Last successful sync: ${new Date(x.fetched_at).toLocaleString()} · ${x.warnings?.length||0}  warnings`;$('#metrics').innerHTML=[['Results',all.length],['Projects',[...new Set(all.map(e=>e.source?.repository).filter(Boolean))].length],['Added',c.added?.length||0],['Updated',c.updated?.length||0]].map(x=>`<div class="metric"><b>${x[1]}</b><span>${x[0]}</span></div>`).join('');fill('#arxiv',all.flatMap(e=>cls(e).arxiv||[]));fill('#msc',all.flatMap(e=>cls(e).msc2020||[]));render();$('#changeRows').innerHTML=[['Added',c.added||[]],['Updated',c.updated||[]],['Temporarily absent',c.absent||[]]].map(([n,ids])=>`<h3>${n} (${ids.length})</h3><p>${ids.map(id=>esc(all.find(e=>e.id===id)?.title||id)).join('、')||'None'}</p>`).join('');$('#history').innerHTML=(x=>x.history||[])(x).slice(0,30).map(h=>`<div class="history">${h.date}　<a href="data/${h.path}">结果快照 JSON ↓</a></div>`).join('')||'暂None历史';$('#warnings').innerHTML=(x.warnings||[]).map(w=>`<p>${esc(w.path||w.id)}：${esc(w.error)}</p>`).join('')||'None异常'});
['q','arxiv','msc','sort'].forEach(id=>$('#'+id).oninput=()=>{page=1;render()});$('#reset').onclick=()=>{['q','arxiv','msc'].forEach(id=>$('#'+id).value='');page=1;render()};$('#prev').onclick=()=>{page--;render()};$('#next').onclick=()=>{page++;render()};document.body.onclick=e=>{let t=e.target.closest('[data-tab]');if(t){document.querySelectorAll('[data-tab]').forEach(x=>x.classList.remove('active'));t.classList.add('active');document.querySelectorAll('.panel').forEach(x=>x.hidden=x.id!==t.dataset.tab)}};


